//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class akun
    {
        public int id_akun { get; set; }
        public string nama_akun { get; set; }
        public string email { get; set; }
        public string password { get; set; }
    }
}
