//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class anggota
    {
        public string no_anggota { get; set; }
        public string nama_ang { get; set; }
        public string alamat { get; set; }
        public string kota { get; set; }
        public string no_telp { get; set; }
        public string pekerjaan { get; set; }
        public string no_simp { get; set; }
    }
}
