//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KoperasiEntities2 : DbContext
    {
        public KoperasiEntities2()
            : base("name=KoperasiEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<akun> akuns { get; set; }
        public virtual DbSet<anggota> anggotas { get; set; }
        public virtual DbSet<detail_simpanan> detail_simpanan { get; set; }
        public virtual DbSet<pinjaman> pinjamen { get; set; }
        public virtual DbSet<simpanan> simpanans { get; set; }
        public virtual DbSet<trans_pinjaman> trans_pinjaman { get; set; }
        public virtual DbSet<trans_simpanan> trans_simpanan { get; set; }
    }
}
