//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pinjaman
    {
        public int kd_pinj { get; set; }
        public string jns_pinj { get; set; }
        public Nullable<double> max_pinj { get; set; }
        public Nullable<double> max_ang { get; set; }
        public Nullable<double> bunga { get; set; }
    }
}
