//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trans_simpanan
    {
        public int id_tsimpan { get; set; }
        public string no_simpan { get; set; }
        public Nullable<System.DateTime> tglsimpan { get; set; }
        public string jenis { get; set; }
        public Nullable<double> saldo { get; set; }
        public string no_ang { get; set; }
    }
}
